# Generated by Django 4.2.30 on 2026-06-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE cita ADD COLUMN fecha_creacion DATETIME NULL DEFAULT CURRENT_TIMESTAMP;')
    ]
