# Generated by Django 4.2.30 on 2026-06-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20260622_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='TipoInmueble',
        ),
        migrations.RemoveField(
            model_name='usuariorol',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='UsuarioRol',
        ),
    ]
